version: "3.9"
services:  
  app_php:
    build:
      args: 
        user: user
        uid: S-1-5-21-41059321-2708555032-851686773-1001
      context: ./
      dockerfile: Dockerfile
    image: app_php
    container_name: app_php
    working_dir: /var/www/
    ports:
      - 9000:9000
    volumes:
      - ./www:/var/www
    networks:
      - app
  app_db:
    image: postgres:14.2-alpine
    hostname: app_db
    container_name: app_db
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app
  
  app_db_mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app_server:
    image: nginx:alpine
    container_name: app_server 
    working_dir: /var/www
    ports:
      - 80:80
    volumes:
      - ./www:/var/www
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/conf.d:/etc/nginx/conf.d/
      - ./server/sites/:/etc/nginx/sites-available/
      - ./server/sites/:/etc/nginx/sites-enabled/
    networks:
      - app
networks:
  app:
    driver: bridge
