version: "3.9"
services:  
  web_php:
    build:
      context: ./
      dockerfile: Dockerfile
    image: web_php
    container_name: web_php
    working_dir: /var/www/
    ports:
      - 9000:9000
    volumes:
      - ./www:/var/www
    networks:
      - web 
  web_pgsql:
    image: postgres:14.2-alpine
    hostname: web_pgsql 
    container_name: web_pgsql 
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - 5432:5432
    volumes:
      - ./db/pgsql/:/var/lib/postgresql/data
    networks:
      - web
  web_mysql:
    image: mysql
    hostname: web_mysql 
    container_name: web_mysql 
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql/:/var/lib/mysql
    networks:
      - web
  web_server:
    image: nginx:alpine
    container_name: web_server 
    working_dir: /var/www
    ports:
      - 80:80
    volumes:
      - ./www:/var/www
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/conf.d:/etc/nginx/conf.d/
      - ./server/sites/:/etc/nginx/sites-available/
      - ./server/sites/:/etc/nginx/sites-enabled/
    networks:
      - web 
networks:
  web:
    driver: bridge
